PUT http://127.0.0.1:5500/api/v1/users/019a4f69-4b67-73af-93e3-5d09c65bff65 HTTP/1.1
Content-Type: application/json

{
    "email": "example2@example.com",
    "password": "password1234",
    "company": "Example AG",
    "name": "Alfred",
    "surname": "Probador",
    "street": "Examplestreet",
    "postalCode": "10000",
    "city": "Exampletown",
    "country": "United States of Example",
    "phoneNumber": "+11 223 34 45 56",
    "coordinates": { 
        "latitude": 34.325, 
        "longitude": 44.356 
    }
}
